[tables]
admin = "UPDATE ADMIN SET ADMIN.RPT_YR = 0, ADMIN.MSMT_YR = 0, ADMIN.REGIME = 'NONE', ADMIN.PLAN_YR = 0 WHERE ADMIN.FLAG > 0"
cruise = 'UPDATE ADMIN INNER JOIN CRUISE ON ADMIN.STD_ID = CRUISE.STD_ID SET CRUISE.PLOTS = 0, CRUISE.TPH_ERR = 0, CRUISE.BA_ERR = 0, CRUISE.CCF_ERR = 0, CRUISE.CUB_ERR = 0, CRUISE.BRD_ERR = 0 WHERE ADMIN.FLAG>0'
dbhcls = 'DELETE DBHCLS.*, ADMIN.FLAG FROM ADMIN INNER JOIN DBHCLS ON ADMIN.STD_ID = DBHCLS.STD_ID WHERE ADMIN.FLAG>0'
dibcls = 'DELETE DIBCLS.*, ADMIN.FLAG FROM ADMIN INNER JOIN DIBCLS ON ADMIN.STD_ID = DIBCLS.STD_ID WHERE ADMIN.FLAG>0'
dwood = 'DELETE ADMIN.FLAG, DWOOD.* FROM ADMIN INNER JOIN DWOOD ON ADMIN.STD_ID = DWOOD.Std_ID WHERE ADMIN.FLAG>0'
habdens = 'DELETE ADMIN.FLAG, HABDENS.* FROM ADMIN INNER JOIN HABDENS ON ADMIN.STD_ID = HABDENS.Std_ID WHERE ADMIN.FLAG>0'
habitat = 'DELETE ADMIN.FLAG, HABITAT.* FROM ADMIN INNER JOIN HABITAT ON ADMIN.STD_ID = HABITAT.Std_ID WHERE ADMIN.FLAG>0'
habspp = 'DELETE HABSPP.* FROM HABSPP'
plancut = 'DELETE PLANCUT.* FROM PLANCUT'
planres = 'DELETE PLANRES.* FROM PLANRES'
plansrt = 'DELETE PLANSRT.* FROM PLANSRT'
snags = 'DELETE ADMIN.FLAG, SNAGS.* FROM ADMIN INNER JOIN SNAGS ON ADMIN.STD_ID = SNAGS.STD_ID WHERE ADMIN.FLAG>0'
stand = 'DELETE ADMIN.FLAG, STAND.* FROM ADMIN INNER JOIN STAND ON ADMIN.STD_ID = STAND.STD_ID WHERE ADMIN.FLAG>0'
standsrt = 'DELETE ADMIN.FLAG, STANDSRT.* FROM ADMIN INNER JOIN STANDSRT ON ADMIN.STD_ID = STANDSRT.STD_ID WHERE ADMIN.FLAG>0'
